### ISSUE TITLE
순환 참조 오류 ?

### ISSUE THREAD

**Issue by JangKroed** [JangKroed/nestjs_starting#1]
로그 : [Nest] 18092  - 2023. 06. 19. 오후 2:41:02   ERROR [ExceptionHandler] Nest cannot create the CatsModule instance.
The module at index [2] of the CatsModule "imports" array is undefined.

Potential causes:
- A circular dependency between modules. Use forwardRef() to avoid it. Read more: https://docs.nestjs.com/fundamentals/circular-dependency
- The module at index [2] is of type "undefined". Check your import statements and the type of the module.

Scope [AppModule -> CatsModule -> AuthModule]
Error: Nest cannot create the CatsModule instance.
The module at index [2] of the CatsModule "imports" array is undefined.

Potential causes:
- A circular dependency between modules. Use forwardRef() to avoid it. Read more: https://docs.nestjs.com/fundamentals/circular-dependency
- The module at index [2] is of type "undefined". Check your import statements and the type of the module.

Scope [AppModule -> CatsModule -> AuthModule]
    at DependenciesScanner.scanForModules (C:\Users\godhy\Desktop\inflearn\nestjs_starting\node_modules\@nestjs\core\scanner.js:53:23)
    at DependenciesScanner.scanForModules (C:\Users\godhy\Desktop\inflearn\nestjs_starting\node_modules\@nestjs\core\scanner.js:61:32)      
    at DependenciesScanner.scanForModules (C:\Users\godhy\Desktop\inflearn\nestjs_starting\node_modules\@nestjs\core\scanner.js:61:32)      
main.ts:8:15)

**Comment by JangKroed** [comment]
강의를 보던 중 순환참조되어 해결책으로 forwardRef 함수 사용하였는데도 오류 발생.

**Comment by JangKroed** [comment]
cats.module.ts에서 imports 부분 2번 인덱스부분이 문제라고 했는데, 사용하는건 1번 인덱스 까지여서 코드를 자세히 보니 쉼표 (,)가 줄바꿈 뒤에 들어가있어 문제가 발생하였다,,,
